//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web02.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class studenttbl
    {
        public string sno { get; set; }
        public string sname { get; set; }
        public string scourse { get; set; }
    }
}
